[[CMake]]
arch = "aarch64"
git-tree-sha1 = "fbc4e113bc0b6f457bda52ab3d646f575dbd260b"
os = "macos"

    [[CMake.download]]
    sha256 = "b11a1f949d1a37377327cee2e9e5264bc2ccf0807420cbde4fe3519f475c069d"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.23.3+0/CMake.v3.23.3.aarch64-apple-darwin.tar.gz"
[[CMake]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "43c401b184c59ac960af28916ffc609fc50d4bf5"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "4a1b3aa6fadb26a1dbcaebc88b7093468ecda4981662ade3ad4b99c97321aca0"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.23.3+0/CMake.v3.23.3.aarch64-linux-gnu-cxx03.tar.gz"
[[CMake]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "85897881d0c31c5cdcdde8f30140a4e938cbde47"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "62a2a6d050b75d0fff0623c22826f839ecf2074c70a094cc510789e2cf8d046b"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.23.3+0/CMake.v3.23.3.aarch64-linux-gnu-cxx11.tar.gz"
[[CMake]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a6ec5c694becea1e13ba7efddae7dec5634e09b1"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "351cb1b273dad4eb66773e9e70dc1fe51be945f40174e7bde262a6a2fbf76ca5"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.23.3+0/CMake.v3.23.3.aarch64-linux-musl-cxx03.tar.gz"
[[CMake]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c75b4c0b47fd2cbdae8feab40f3f717223ab687a"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "36e641bc18894228045fb8b11a03c692bd6841296ece5601a1bedb4ebadab9db"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.23.3+0/CMake.v3.23.3.aarch64-linux-musl-cxx11.tar.gz"
[[CMake]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "46dec732e10773b2da8b29e395f3925869a72fda"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "2de9eed7999748fe6da74074cb6b3b2897ae4d22797a6149cd7041810c47be3a"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.23.3+0/CMake.v3.23.3.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[CMake]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bebc8951526123cf95e26c9ed914fafb6e766898"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "48fff5ef1c36c1f54109e61d74f3988e653feedacd7c9071c238b5f921539be5"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.23.3+0/CMake.v3.23.3.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[CMake]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "89068d9e4c8c5a322b606ce41fbbf69f1e8ff4fc"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "8274d108842e5d33a94492c632cd59b3166bbd394cd1115e862352bb180afd15"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.23.3+0/CMake.v3.23.3.armv6l-linux-musleabihf-cxx03.tar.gz"
[[CMake]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "652228d7ab12158116b6dd9caae2f7232f4aecea"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "5cc5d6e3907edbc77ac6e4fe766a195abcbe8dc5e9d3180011c846c66c8cf534"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.23.3+0/CMake.v3.23.3.armv6l-linux-musleabihf-cxx11.tar.gz"
[[CMake]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "03a69a55a42b081f6c9ba31b88945183156319a8"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "7b075e5aaa4a599febf9f5a6f6eae6e1dc5f7b2afa5ca678e990390cadf374bb"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.23.3+0/CMake.v3.23.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[CMake]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e647fd2417de59e2052bb0c91a6ec592a87c8a41"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "acb05e43033dd496c84da0304752a74ea955707e325022110b991b6d879e223c"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.23.3+0/CMake.v3.23.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[CMake]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a67959d39e7336c5ec247323f90ae4bd6756aa0c"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "eaae0b878dac8492c0efadad85d0541697d0224deb0eddf1db60764e9d57f16e"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.23.3+0/CMake.v3.23.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[CMake]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4c04b56834a747664a7000250ea990b020a94f79"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "9e3825097ac71473acd0062c1df8e71c5be41a517a5e7ca94da49ec0f9c7ef9c"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.23.3+0/CMake.v3.23.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[CMake]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a3e7649ec4c0309570cfdf501b8bd860eff5b40d"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "d45646dc5fffbb6c4497e16740e4c55ea94af09e180a7f3e607fb4be9e47adbb"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.23.3+0/CMake.v3.23.3.i686-linux-gnu-cxx03.tar.gz"
[[CMake]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8101e59857af8a1d7931b382c7cd3d1e5e16ebe4"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "3a6c05b564136867741522a37e4722b57f9fe3762f5c4f387cdcd1264b8854da"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.23.3+0/CMake.v3.23.3.i686-linux-gnu-cxx11.tar.gz"
[[CMake]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1b7db5d0546edce5e7dac05851e990cf8ae4cd37"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "50bf89b431b8c0554e24278ee65152ca6c79007204574764076f02ed36c99956"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.23.3+0/CMake.v3.23.3.i686-linux-musl-cxx03.tar.gz"
[[CMake]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "672b0ae5aec47905811a090288901cfdbe938f4e"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "b0ff7308cd16b0b7f965b43825fc5a66280a0206cbc46d2db35bc6aaebea304c"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.23.3+0/CMake.v3.23.3.i686-linux-musl-cxx11.tar.gz"
[[CMake]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "643ea224c6b3760f93e7e29fefec6d996aca7970"
os = "windows"

    [[CMake.download]]
    sha256 = "dc93138c33f1373c01075b0e3b3877cc1a2ba366dd2d98f4aed115dce6469a79"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.23.3+0/CMake.v3.23.3.i686-w64-mingw32-cxx03.tar.gz"
[[CMake]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8f8c64d502bd2d9c40c19e146bbe0a4f3ac97846"
os = "windows"

    [[CMake.download]]
    sha256 = "06d163230c75c73369ea324d6f8a864be665864ddb0beeb956bdcaddcdb593ca"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.23.3+0/CMake.v3.23.3.i686-w64-mingw32-cxx11.tar.gz"
[[CMake]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5a656c19adda40a846c21bc8627eac30b1186b5b"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "87b43277785b5b82e9d05b19bd9d415072b335be58e80526dae2b75ebccb0fdb"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.23.3+0/CMake.v3.23.3.powerpc64le-linux-gnu-cxx03.tar.gz"
[[CMake]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fdb9f722c56955f4b50d7cb487e22f41156b1f44"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "be6def56cc0afff79a2d7e66976b5cd728b300214b4071fc0bff3059ae10e009"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.23.3+0/CMake.v3.23.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[CMake]]
arch = "x86_64"
git-tree-sha1 = "d8edae043fa89272938feb367e3fd14b549bd3e3"
os = "macos"

    [[CMake.download]]
    sha256 = "b4038f9e8f62053e58ecd5b38fb328751de05daffb1fc6973c33dac6bb2aac6a"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.23.3+0/CMake.v3.23.3.x86_64-apple-darwin.tar.gz"
[[CMake]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5a7c182d7fc1616f149bc1227648d31a7f502639"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "81f8c5f008a390d659bbf16394d37341c8ead042463ae818fc495f09ede81f94"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.23.3+0/CMake.v3.23.3.x86_64-linux-gnu-cxx03.tar.gz"
[[CMake]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "43125cf645887db780193212efa134997d4b003b"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "11ff08ea969ac0c67357f5374e3317e7950c2ae9abed3907f531986ba56459c0"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.23.3+0/CMake.v3.23.3.x86_64-linux-gnu-cxx11.tar.gz"
[[CMake]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "684c23721fd3bd54c69291be307d69570903076a"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "37e3e484a572163da6c755eccac3085eabb10428b1790acc3e2fea0d1788f4c8"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.23.3+0/CMake.v3.23.3.x86_64-linux-musl-cxx03.tar.gz"
[[CMake]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "273e92915e48b2be7e121cdacffc970052ad62a2"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "1225ebe56f2af6b731b2d99e98839b4b1dabd573889bba6e4137d188854ce5cc"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.23.3+0/CMake.v3.23.3.x86_64-linux-musl-cxx11.tar.gz"
[[CMake]]
arch = "x86_64"
git-tree-sha1 = "df1fbe9324a980bbaff053149248a6090f2cf8dd"
os = "freebsd"

    [[CMake.download]]
    sha256 = "64993550d0bf8ce9bb079d0fad0e7867b33faf7334c7d0d39dd0abeed72b108e"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.23.3+0/CMake.v3.23.3.x86_64-unknown-freebsd.tar.gz"
[[CMake]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fffb757822df0ec2505e253c13e7af244e978189"
os = "windows"

    [[CMake.download]]
    sha256 = "f4f643f0af57cfcf82a85851b579dd7524e99e8b8c7e83e1eae5cbc1ae7729d8"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.23.3+0/CMake.v3.23.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[CMake]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3df284ed3d303d721f46083242e0941ddad5ad77"
os = "windows"

    [[CMake.download]]
    sha256 = "ea802cb1d6c913ed3222c4d87cfb99af3dfb100ada8cd1cff76ab180f27f6442"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.23.3+0/CMake.v3.23.3.x86_64-w64-mingw32-cxx11.tar.gz"
