[[CMake]]
arch = "aarch64"
git-tree-sha1 = "386e076ebe24153cd7feb48f68512cacfb1891f9"
os = "macos"

    [[CMake.download]]
    sha256 = "83342c56e4015fef0fd5a87bd055b7be07fe16d9c2443e54a87815b5c823e3d2"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+1/CMake.v3.29.3.aarch64-apple-darwin.tar.gz"
[[CMake]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9a4a3151c1e8c4fe549a0ba30901e75e88139ef1"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "2c03d134711c666f7a922f63de03966b6fe0bd4861e6640301cf24ed13cb8a4d"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+1/CMake.v3.29.3.aarch64-linux-gnu-cxx03.tar.gz"
[[CMake]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9b039693ba515ca59ac9ad80fd7f93a7ce7989df"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "a948e31b32fbbf8fb1cc6e2ce80f70e373bc1249bffbc4aa7ed96ae6adfc7140"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+1/CMake.v3.29.3.aarch64-linux-gnu-cxx11.tar.gz"
[[CMake]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e353e152af69b2b338e1d9c91eb8cf08846aa1f1"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "fc3065d9661e219144852bb3dc772a2380aab3e1e919f7fac24f28f930b5a2c2"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+1/CMake.v3.29.3.aarch64-linux-musl-cxx03.tar.gz"
[[CMake]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "84434e572556ae7e108778e3c240503a7208082e"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "edd36170876631be07d08676bac7b36603f3253b2fb1abcdcdf19845daf093bf"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+1/CMake.v3.29.3.aarch64-linux-musl-cxx11.tar.gz"
[[CMake]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c8833779d9d73140deb736a12486e7a93a8046b6"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "21ac61cb052068b70acdea4d07b8a6e679413328a283055868f56e5196236525"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+1/CMake.v3.29.3.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[CMake]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c18b0a7d11766413046a6f9a727de9fc6a31d655"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "dfa87fd705cc4c7f335e5f0202d125a10b1980856188e4eb9396e9c14f98f562"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+1/CMake.v3.29.3.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[CMake]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d3e29368bbd65f344047a5f13c4d95829dc75b06"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "083a09ecace34000aef07b9c9c282d7df804c6cb887d765934e1365201f1dd3b"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+1/CMake.v3.29.3.armv6l-linux-musleabihf-cxx03.tar.gz"
[[CMake]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3204cd5fd273764abf59352f9a00dc4cab19e1a8"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "099ce2b4d3b63103aa692b6cf6f29b2f38378327d494e232d7e63903be5c5b31"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+1/CMake.v3.29.3.armv6l-linux-musleabihf-cxx11.tar.gz"
[[CMake]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5472dc8e3e17528352c3a6899331521a712e9845"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "503b0ddcc41f821f3cf27d2d19fa1cb8ca33ab8a47a4a1dd1d667e245045c060"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+1/CMake.v3.29.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[CMake]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd7124161e798a5122b69ca909cf1464c041e8a6"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "440516553b307624df2ed3901bb0f12fa2b9e1ad4a3a76d29003dec40e23a6de"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+1/CMake.v3.29.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[CMake]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0553084b8bdeb30e2791a050feaab3c661bf25b1"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "bf8321a19170ef11f3faf0b23c7b73e8bcc8bc77e80d9d55851e05950b548bf1"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+1/CMake.v3.29.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[CMake]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5220cd0cb025010473768f787bf83b63bde6015b"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "31ebe6c967f4f12a07b0bad7850b2b512c2a9fc79e864681be87d6a03efca619"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+1/CMake.v3.29.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[CMake]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d5ce6b02cd30c57d41d471d81bc50492727d1658"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "0462874b381a41cb826678bf92fd8e24aff207e7a9634f0a55e9c1a3795ea6ea"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+1/CMake.v3.29.3.i686-linux-gnu-cxx03.tar.gz"
[[CMake]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0906334304220b3cfe0c01b569d4d8a4cec32296"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "0d4d75925e2e95d974fefb825c0d69af9b51ec85b16e7d40d6eece5bc7482ee7"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+1/CMake.v3.29.3.i686-linux-gnu-cxx11.tar.gz"
[[CMake]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ef1c8ea56676b12dc5b0d642128bc1c2c35ef62c"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "38d71848b6c70c24c7eea1646944968911b09064b502476fee2ae2bf8e7e4482"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+1/CMake.v3.29.3.i686-linux-musl-cxx03.tar.gz"
[[CMake]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "553139b30429bb48463470e077a7a2a290eb4d07"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "2aeeb546786c6c7ef8ff52c68ad2ea1e132474f987d8adfa9dc322bc7234d4f6"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+1/CMake.v3.29.3.i686-linux-musl-cxx11.tar.gz"
[[CMake]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e10e8ab77afe54d2bbc0b365e5048ad2f5841056"
os = "windows"

    [[CMake.download]]
    sha256 = "e6c0c0a88c97ea40967503c79ea21d1354b942c6d70d1ad63aa96d0ed0b7686f"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+1/CMake.v3.29.3.i686-w64-mingw32-cxx03.tar.gz"
[[CMake]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c521ee7762e0a0f2bce17687ac3677a181ca1ad3"
os = "windows"

    [[CMake.download]]
    sha256 = "9c5463da2ae0fdf688666c1afe8a4adef4d17f7c1e7242622e9fb1f6965676f5"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+1/CMake.v3.29.3.i686-w64-mingw32-cxx11.tar.gz"
[[CMake]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7cc9e6d0963144b36033d011078d70bc9701a65d"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "d96558bfe2f3df77823e9d069be7761f1d32acd446949d24be3507b6d3ee4f03"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+1/CMake.v3.29.3.powerpc64le-linux-gnu-cxx03.tar.gz"
[[CMake]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6ceba1adc8e30ae92ce82c3498d933b457aa29e3"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "c5548cd7b53df6263db0124c533bf9ed03fa80280395db56635e83e155573c69"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+1/CMake.v3.29.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[CMake]]
arch = "x86_64"
git-tree-sha1 = "e0a331044b2221ee14110da53b9188ad65ef96ee"
os = "macos"

    [[CMake.download]]
    sha256 = "67a3c1de5968557a2a20ac91eed6c8581e6fd8ef0e61fccad57deeb980bd4976"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+1/CMake.v3.29.3.x86_64-apple-darwin.tar.gz"
[[CMake]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0347dfdcd93f68e1478e04a4bfb8ef3e713ed7cd"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "a51e9d912595121071fbffcbec3e94c96c4f6a7adb2443aee6a20103a1428d8b"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+1/CMake.v3.29.3.x86_64-linux-gnu-cxx03.tar.gz"
[[CMake]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a8d27fab138de0785cb0eb3157737c9fce5d6793"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "7651c52644bd463a2189e5a0c221e1a1e35ca32fd72252c7501f52439d00139e"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+1/CMake.v3.29.3.x86_64-linux-gnu-cxx11.tar.gz"
[[CMake]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a495b961763e7e6e1bd7652cd457eee57482e77f"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "cce46cdee75ced3a1a1630b54c7b15d6a6eefa0e3b54a49e543c3e102c162011"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+1/CMake.v3.29.3.x86_64-linux-musl-cxx03.tar.gz"
[[CMake]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "53625eb985d20695eae073b4aa6cc749e1dce7aa"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "ac4a2d0d3c2a23c4d086c02687184e0b83278655a27f41da17c6ded05a27946d"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+1/CMake.v3.29.3.x86_64-linux-musl-cxx11.tar.gz"
[[CMake]]
arch = "x86_64"
git-tree-sha1 = "9c6eba1275d952a1cadd07f57c3efad9e8728c1c"
os = "freebsd"

    [[CMake.download]]
    sha256 = "99628069cbb71105717f06da51c05aa77bcd29c9fd32e82b677877525a319050"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+1/CMake.v3.29.3.x86_64-unknown-freebsd.tar.gz"
[[CMake]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "507f4b5fe890753f66d3fd612c6878f55b586937"
os = "windows"

    [[CMake.download]]
    sha256 = "2bf05939b55f5db17497a7097d85ae9b56eea5d23a2af7e664ebe7d14ff1507a"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+1/CMake.v3.29.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[CMake]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "289aeafd1b1b67b2c1778ab23c96199e1d91e589"
os = "windows"

    [[CMake.download]]
    sha256 = "389475ce64ca4a649929c39a0619dfa108e33df45bade88bcbeec8e2ca338a10"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+1/CMake.v3.29.3.x86_64-w64-mingw32-cxx11.tar.gz"
