[[CMake]]
arch = "aarch64"
git-tree-sha1 = "a1f6cd40f69ec1286c28faf4ddfef9c74ff689dd"
os = "macos"

    [[CMake.download]]
    sha256 = "abb83f7dfcb777465382b40a80a145275773e06f27e2deab7b1587554723d488"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.3+0/CMake.v3.31.3.aarch64-apple-darwin.tar.gz"
[[CMake]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8f9fb1f7d890cf6d79a237b3ea6ed18c3e62afb1"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "aac1659a2094c7ab3870eeb62415fcfa4ae0bf587bd21142fec1c80b58b0a382"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.3+0/CMake.v3.31.3.aarch64-linux-gnu-cxx03.tar.gz"
[[CMake]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ef09489090a06b8e0d381d6b720646972831c28"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "530849ea43a93b2ac0277822e4c887ff655732298ece1d94f68845e1aab6cd0a"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.3+0/CMake.v3.31.3.aarch64-linux-gnu-cxx11.tar.gz"
[[CMake]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3e6ace01b9c5156ad5011a132def40d5d90afba0"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "04fa5fb836ba8cafdc14fffba12c66cf6ea893a1419bacdf7cd43da1b8085df9"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.3+0/CMake.v3.31.3.aarch64-linux-musl-cxx03.tar.gz"
[[CMake]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0e89ba2f1caf40c9cdb2c5fade4e6d2f49bbad5a"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "4729e566080ea3006c269c687cc35c522aaa5721ec1eae059d81fdeed3795f77"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.3+0/CMake.v3.31.3.aarch64-linux-musl-cxx11.tar.gz"
[[CMake]]
arch = "aarch64"
git-tree-sha1 = "edc9cc30d9d28091b23dc3007af2de7116f134a2"
os = "freebsd"

    [[CMake.download]]
    sha256 = "1ad3634284b49a9d9714e9d79d5cd93bd142c8d1602e40570d98accd775f9677"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.3+0/CMake.v3.31.3.aarch64-unknown-freebsd.tar.gz"
[[CMake]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b8af6464b5432390644544ed4bb10cb07be7200e"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "8622b385c5a5b85fb30b2d8ff979899cd2e92001c188fe27de0782c469e7c331"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.3+0/CMake.v3.31.3.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[CMake]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c0ba26154c511ac89e7b99859eab51e2ab6f0b2d"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "32f92d22a07be65e16cba85932f5c63502468053f1180d897840d53e4039a129"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.3+0/CMake.v3.31.3.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[CMake]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "81e74e6d539d50a8ad85e378cbff0cf1172bd538"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "0218bcbdab9524b4a82af997e85891a32b65f513f71e4d2cee6da4ca5649cd75"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.3+0/CMake.v3.31.3.armv6l-linux-musleabihf-cxx03.tar.gz"
[[CMake]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "629dfa9c99ac56cecc676b4d5b808a90069ad001"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "8a1aeeed5756c124f7763122817c9805159b79b12cd374af9eacc84b675b009a"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.3+0/CMake.v3.31.3.armv6l-linux-musleabihf-cxx11.tar.gz"
[[CMake]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6abb952acfdea6b094a5e2249e0c6bddb1a3bf63"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "01439c5771aabf84ead42bf9369df780f572b8cfd3acc5fe3e27e56cebb43e12"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.3+0/CMake.v3.31.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[CMake]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "04fd258cb774649665c32650343f785c425e6802"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "efa1f424c13c1152f54262a2a15e61e7e6c03b5ece04e5aa73fb883a1f59eba0"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.3+0/CMake.v3.31.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[CMake]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ec73a9cd0d04f49f354a1412747048f63c7a598e"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "7941b0bc7d291ab4a05fb4d08feca6b7e52224355d7436d4838118a418e60b0d"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.3+0/CMake.v3.31.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[CMake]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4b8e002381a8a8f288be3f8ae8a411ac63d0951b"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "9e1be236315fb301293cc1ad0bd1edce6c7b0dfb8cf456fe85dc4f7d62d95501"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.3+0/CMake.v3.31.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[CMake]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f0554a6f5c55e92e1b4677155ecb1ebf7c6d2f33"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "685f160d3714514d74215c54e7557edbf2505f93b16207adebc3e71eb320884f"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.3+0/CMake.v3.31.3.i686-linux-gnu-cxx03.tar.gz"
[[CMake]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c04ee725a9ac23abbbb9b6087bd603e3d1ea988e"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "271f9cf77706bfc8c94e6b04d1232d74c8309f06eafa160910acbedd22fb08f7"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.3+0/CMake.v3.31.3.i686-linux-gnu-cxx11.tar.gz"
[[CMake]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fbf54215a0824cac2cdd566aeb7321c03b0c7b72"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "426b3c9f4a6fd78d0c99f881d506a5369271cac3b1c07d06725f939884338940"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.3+0/CMake.v3.31.3.i686-linux-musl-cxx03.tar.gz"
[[CMake]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4b676914c5644ad8a018170bb4484fe4563cd473"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "5bc92a06a0ac1734328d93d1cb72e8b07dc0cd0ed348ccb8ddc7439a0bfc2d33"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.3+0/CMake.v3.31.3.i686-linux-musl-cxx11.tar.gz"
[[CMake]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cc7d10d549d766111c1c65614b7413970438b8e6"
os = "windows"

    [[CMake.download]]
    sha256 = "e9e86c98bb21b43cee94422b86cd1c5d04bf722200d4c7a028666a0ecf9f2d59"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.3+0/CMake.v3.31.3.i686-w64-mingw32-cxx03.tar.gz"
[[CMake]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4c01d164c4970d5b7a49e1990354661035c998dc"
os = "windows"

    [[CMake.download]]
    sha256 = "f48dbe1bf617a7033ab15fa329eb2ac5f15ceecffbd56f72cc972020945828bc"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.3+0/CMake.v3.31.3.i686-w64-mingw32-cxx11.tar.gz"
[[CMake]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e82310f29f313e009e0a1a04f509e09bcc46b44c"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "555b8358c58c6f2c2227019fb77f471cd2e65f4db1788fef7bcd52057d112dce"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.3+0/CMake.v3.31.3.powerpc64le-linux-gnu-cxx03.tar.gz"
[[CMake]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7bf63a3c08b132d8e8c3a62ac2ec81060e7dce50"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "a518fb057a1b5f04fa9b7d28eee7f10b527d00cc21e70f9e7a5996c2da800fc0"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.3+0/CMake.v3.31.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[CMake]]
arch = "x86_64"
git-tree-sha1 = "f441a66d91146d283e5fb75ea63c0bf2172f301e"
os = "macos"

    [[CMake.download]]
    sha256 = "8513c363579b21f57fc72f32c5b53c489bb073131cfd3bf62d5040d0a622fc63"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.3+0/CMake.v3.31.3.x86_64-apple-darwin.tar.gz"
[[CMake]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fb220ccaa3df1ef35ab242f92cbe82f850a02518"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "f2ef72967915204f324a8513422994c1f604bbdd5ca2d704f12cac0e861afdd2"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.3+0/CMake.v3.31.3.x86_64-linux-gnu-cxx03.tar.gz"
[[CMake]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "53ba193cf5c8f9c87e6c68c6229415fd7b4842dc"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "d1c27bf1277a70b097b64c7145f89262718db33430d641b096ee8af2872bc523"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.3+0/CMake.v3.31.3.x86_64-linux-gnu-cxx11.tar.gz"
[[CMake]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ad76d1da63e129bd9ef8b952f247f7d48c7c9a9c"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "83eefd1f3053ca97ab7577b8545c5fe7b47a8d198ad901cce57577a226453e4a"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.3+0/CMake.v3.31.3.x86_64-linux-musl-cxx03.tar.gz"
[[CMake]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c1088a64ad5fdfb6e0b56177656bbf60cd0c8569"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "7cfa9372561a77896a8a8bf454c8f042c4f36d233ed11fb767168c303bc02941"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.3+0/CMake.v3.31.3.x86_64-linux-musl-cxx11.tar.gz"
[[CMake]]
arch = "x86_64"
git-tree-sha1 = "df3e12389376300819eb675de3e5f3570b726d0c"
os = "freebsd"

    [[CMake.download]]
    sha256 = "06f62cba53cc7e8f24a283cf550f0bbc2a9db50aefdcbb5111b59e889e8cd1de"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.3+0/CMake.v3.31.3.x86_64-unknown-freebsd.tar.gz"
[[CMake]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e5859e8f79ab76f63508262e60478a57d4185614"
os = "windows"

    [[CMake.download]]
    sha256 = "12903b1de8e99da74bc7006db2275b286e3a631f631795d6f74df94cfd774355"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.3+0/CMake.v3.31.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[CMake]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "06abc60be18b2e713ae77641581dcf6e29c8f9a5"
os = "windows"

    [[CMake.download]]
    sha256 = "0a82194687bc1ce09c051af0a2491ecd9f6de3b63455c36d4a91e66eb3561834"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.3+0/CMake.v3.31.3.x86_64-w64-mingw32-cxx11.tar.gz"
