[[CMake]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2ac1ec8798c090da38f97b3ca7b9e2c8420d3f52"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "fbea6b0bc763b2baf89d7f93c54d33b565a208468337d0df1ecb25ad46808d2a"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.19.2+0/CMake.v3.19.2.i686-linux-gnu-cxx11.tar.gz"
[[CMake]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "59131a263ca6b3cdf239dcb8aff0560053a2ea3a"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "8ce87bf78f796846ee86457d1e92e35861c4d9da34890417d297b012c684610c"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.19.2+0/CMake.v3.19.2.x86_64-linux-gnu-cxx11.tar.gz"
[[CMake]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4c75a24560bc8ca958cd5abb5e7c3419d05f16b4"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "0b4e148d325d3693237710ec6e44eabaa9e633c4b48a57668a90d07254825087"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.19.2+0/CMake.v3.19.2.x86_64-linux-musl-cxx11.tar.gz"
