[[CMake]]
arch = "aarch64"
git-tree-sha1 = "f1d1e206150c4af939f436a54ed38f6f7a822a37"
os = "macos"

    [[CMake.download]]
    sha256 = "f9f65a69ac1ea4dfb3977a79856b69c000a55377849307fe29ede51c59a07d86"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+0/CMake.v3.29.3.aarch64-apple-darwin.tar.gz"
[[CMake]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d63994f209da4c4eee3c7272acaa821d78522471"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "ac5f3c04f9af63415da2fb668c39fa5bd8447af497012c0053388008fad6731c"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+0/CMake.v3.29.3.aarch64-linux-gnu-cxx03.tar.gz"
[[CMake]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f798e98b02189fc4c8464b7329890ed05fa413ac"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "7ec0331248ff9cae16c9dd67cfb6436c60291882ddb6b0ff47be232c0f569041"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+0/CMake.v3.29.3.aarch64-linux-gnu-cxx11.tar.gz"
[[CMake]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "26442f3bd5a8443cdad9ecccdffec965b83b7ee1"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "8fc297b1de4b7ed6e0534a8db5ff601867bb31d83d153013c49efdc76f1af38a"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+0/CMake.v3.29.3.aarch64-linux-musl-cxx03.tar.gz"
[[CMake]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8baeada4fad134f95c9b24b7bb00415c12852bb7"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "ca8ef06716686cc807dae4ea58a7de6a59de4d6e5486abb2af9424dadfe2a345"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+0/CMake.v3.29.3.aarch64-linux-musl-cxx11.tar.gz"
[[CMake]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a2bb137084bf08c27c96669cab0fb11ca0284b39"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "d3befcf06918e93dfaaef4f3d0d7766f871b0cbdfeea1025dcc569ec6f77ef88"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+0/CMake.v3.29.3.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[CMake]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e5909f3e15980ad0aa807f3baccf504fe4d40a9d"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "2e7e231fd056cde30cbfd2a16c4dc3d25e651d1de8984913a880f51fbf5220f6"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+0/CMake.v3.29.3.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[CMake]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0d0b1dff6deff63644d689059a9fef7373d98ae5"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "4b965dc9a50b21d24bb3ee6cf70097babfedb81c592a85ff138f4b44f07f2a70"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+0/CMake.v3.29.3.armv6l-linux-musleabihf-cxx03.tar.gz"
[[CMake]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "101dda6df6f0d6c80717f6d2ebaac813670c45ef"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "d497be3164927ee9c31e1dd8d56d160d72fc1ad2c6bf75cea1c11d57dbc4c588"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+0/CMake.v3.29.3.armv6l-linux-musleabihf-cxx11.tar.gz"
[[CMake]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5e5b8a87694e42b1c6c8b5b120c6d1baf756c968"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "fa0474ecc7ce94249e5d252e00a90e1686529cecfdfa2c81213f06256becb29c"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+0/CMake.v3.29.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[CMake]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "83cd0046dcf7cb7b9bd7f237849c7bf162058055"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "52d74db4129788899b7a0060a84a3cb7f20c01103c037dbe54e5a723766acb19"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+0/CMake.v3.29.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[CMake]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5073fd30fd33f3e8b821e1f6ef49bb8f47dbcead"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "ee3466cc71a370649879d217bc919a3adfb5820f4eef8bc6254261f161afe0d8"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+0/CMake.v3.29.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[CMake]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4949923eacee4a6b7c20142d473a695942de1360"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "2b8ab69cf18976ac2a5c7c36c8417d63e1fcf988c181170a17805f96af074970"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+0/CMake.v3.29.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[CMake]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "33b383f2d4ba41b66bebd8f98fb495439343db61"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "4fb7b01baa5a23769ecbecf297735fc37607f6390b9a72e955b4646c32d76261"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+0/CMake.v3.29.3.i686-linux-gnu-cxx03.tar.gz"
[[CMake]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3069e2fa343af5af665b76d93a1fd8cd9741851d"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "61b4e24ab0702af52e3a5f9bd10e2c37bae46d295b0b590d48fcd2e34bcfc250"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+0/CMake.v3.29.3.i686-linux-gnu-cxx11.tar.gz"
[[CMake]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "416ef6b81abc6cff16f17f85e136e4ba9a924445"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "f3bce679ccebc121124b008ce85ecc807e0327d796864f12ed1942a84f4503f5"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+0/CMake.v3.29.3.i686-linux-musl-cxx03.tar.gz"
[[CMake]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "14b25ea6d003ec784a055b816d04e029e2ad9cce"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "bb5153f095db47e5a0b9002b728713ca6d6da65043f8497bfca41dd599276c70"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+0/CMake.v3.29.3.i686-linux-musl-cxx11.tar.gz"
[[CMake]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "392d587eda7cfc750aae8590e8bbde419ee07778"
os = "windows"

    [[CMake.download]]
    sha256 = "09865cee11a86ae7c3c62b7176f546eb0b007035f6c1cf53bf5570b6ff7074dd"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+0/CMake.v3.29.3.i686-w64-mingw32-cxx03.tar.gz"
[[CMake]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dd9dd96796018cdd616128c5c5e9a0ead07d9836"
os = "windows"

    [[CMake.download]]
    sha256 = "1eb5dafd926423b2a37f7a6de400b545a27b61a1e79ceabf6ae1a421c498ac0e"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+0/CMake.v3.29.3.i686-w64-mingw32-cxx11.tar.gz"
[[CMake]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "40bb720ea890cb6f4c36e457806ee775fd37e753"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "21fd4498b8efa4e404af3767c6ed31a137a33701d9ba3ed81013396f0a483b54"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+0/CMake.v3.29.3.powerpc64le-linux-gnu-cxx03.tar.gz"
[[CMake]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1a1ca51d7b438543d21b57ebcc6b56b4fa7c2678"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "b79e2a68e88e744266d681c4bf94fba655d0508a09cb063943e3ca5d4cf95fd9"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+0/CMake.v3.29.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[CMake]]
arch = "x86_64"
git-tree-sha1 = "ae2282229a4bd7df3c644a16fb92203083d8bf07"
os = "macos"

    [[CMake.download]]
    sha256 = "e1716bbfc7aa729f33035b356d5377bd3078444330eeef532f9828af0e921e50"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+0/CMake.v3.29.3.x86_64-apple-darwin.tar.gz"
[[CMake]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9b0c64f8e06b4d6ca93516457ed15ac6059aca16"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "d9bdd2f86f4d7563fc2590ef443ae1303300b6f346770bd4a5949c04e65f4327"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+0/CMake.v3.29.3.x86_64-linux-gnu-cxx03.tar.gz"
[[CMake]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ebd7fc10b1ad586d633f7a68ba3757080ab40801"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "2b7cdc2e724d3a3f54201d801b2fc24003f6ec8dba25819a49a48776e765165b"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+0/CMake.v3.29.3.x86_64-linux-gnu-cxx11.tar.gz"
[[CMake]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c5c109a866447d6968cd4f0f538c92a9c85e643c"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "8258fb6edf92c50d9e3cf9f6e003b94c906391d8f0e8130d0168ad19e3141bc5"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+0/CMake.v3.29.3.x86_64-linux-musl-cxx03.tar.gz"
[[CMake]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "41b0dafed6ac55530a76e345f82ed4e4aa6843c7"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "7430f38e71428bdbee71ddb7d68851e661acaba8be2440f020fb6186c02cb572"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+0/CMake.v3.29.3.x86_64-linux-musl-cxx11.tar.gz"
[[CMake]]
arch = "x86_64"
git-tree-sha1 = "e110825aa19232f6e56333c2ece6e82cf5acce62"
os = "freebsd"

    [[CMake.download]]
    sha256 = "9aa4755d2aae7a9128b4ebba5622d1c9a1da6fe02546861aeefbb3da0d6f6ff9"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+0/CMake.v3.29.3.x86_64-unknown-freebsd.tar.gz"
[[CMake]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fa63575eed12ac96361e4b37ecca2bb97cae2b79"
os = "windows"

    [[CMake.download]]
    sha256 = "b0015ec4735d187f7dfd4950b225405918089768e697005f831d8639b4b960fb"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+0/CMake.v3.29.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[CMake]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5adbd39ddf2019d2c9ed9666a6e3a7a175baf6a0"
os = "windows"

    [[CMake.download]]
    sha256 = "f90ccce7a0d8b602c91d50533a5f83961ee522ec19fd20b0dcdf7dfb5a7e5c54"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.29.3+0/CMake.v3.29.3.x86_64-w64-mingw32-cxx11.tar.gz"
