[[CMake]]
arch = "aarch64"
git-tree-sha1 = "3b24e180940d84767f0a4644124545fe402cc41f"
os = "macos"

    [[CMake.download]]
    sha256 = "06cdb39a741ca0ac7bcf12da0e6afc07f8036667124529cfb672d9ca0fc2e491"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.5+0/CMake.v3.31.5.aarch64-apple-darwin.tar.gz"
[[CMake]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "63e4d2fb69d2258ca2eaedcbea643f5591252abd"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "8b28319441106f0d21e956b42d5166a404f4ac06074a56f903da6051960273aa"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.5+0/CMake.v3.31.5.aarch64-linux-gnu-cxx03.tar.gz"
[[CMake]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dcc15a1cd75b101e11a169ca7a789ace0451ccca"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "0a6096f653a41569fc68289d713fbe57ad7bfada9cb8d5bf6c82e8eae8d36e94"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.5+0/CMake.v3.31.5.aarch64-linux-gnu-cxx11.tar.gz"
[[CMake]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "be775a4039f4f75886fa1f501b6ca596a191e27b"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "3fa7cb813c0dd14ca4f82984d01a086124c5699b16c17fe34dfeaf25cda9676e"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.5+0/CMake.v3.31.5.aarch64-linux-musl-cxx03.tar.gz"
[[CMake]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2a197ba9c4df01e41195bdd0aa70100b27c19c3e"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "9082536888c76757151dda760414c8d754662e52c72f924fb168979d4db495b2"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.5+0/CMake.v3.31.5.aarch64-linux-musl-cxx11.tar.gz"
[[CMake]]
arch = "aarch64"
git-tree-sha1 = "094f001d7443359bd2b5bed301b1c521169fbbdd"
os = "freebsd"

    [[CMake.download]]
    sha256 = "01b3ac954603763bf6af45ed2f289d341c7d3c8f90d571d88ca31ed5c49c19b2"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.5+0/CMake.v3.31.5.aarch64-unknown-freebsd.tar.gz"
[[CMake]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "93ac8596733aeb4f1c5690ffab812e2bf6e19eff"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "c8983b055c8912fcade831ddc1c5b01921012848cac041f73f54d5a7868367ec"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.5+0/CMake.v3.31.5.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[CMake]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1974461bd9b18720f57aee9f2d59a2ea6903c769"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "fbbe6fe4c67b716d2b261625d36446f49f63fef3db86470a59dce72ef7d690b5"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.5+0/CMake.v3.31.5.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[CMake]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ef6f77d7f6af297acfa363dd6d2c199ffe34f2e1"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "ec6c421e12611bb80cb4cc3154122a39196f1be20eb1b3b328d8b339da66113f"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.5+0/CMake.v3.31.5.armv6l-linux-musleabihf-cxx03.tar.gz"
[[CMake]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6bd33060797ce1e57bbf53ea74927344a5f5e776"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "1a6ba9115644db6032d756d36802092422d90ed8f1c6006b085a65f86ba4e030"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.5+0/CMake.v3.31.5.armv6l-linux-musleabihf-cxx11.tar.gz"
[[CMake]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7ce57f85c2d34ad479c7986c7199f25fd93c298a"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "a7cffaf14f95f85c981c8cebee717b471e5b2188e655e3af73d4625d57b6856c"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.5+0/CMake.v3.31.5.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[CMake]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6ea7eff9e791a08222d21223a2b2218a35193960"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "9a03ce48744d9e516d248a84e9d3c3f33a466a84b0f07a061d1ed8e25fd7283d"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.5+0/CMake.v3.31.5.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[CMake]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3739ed5f17eb988b6ab83571c9d6a763260362e3"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "f6c01bde5c9d86e3d0a30a7910f211b6ec7260a4c9e253ebd449cad178549065"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.5+0/CMake.v3.31.5.armv7l-linux-musleabihf-cxx03.tar.gz"
[[CMake]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "83bd54fa25d40e5cffc98672669bba4c7d686464"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "0d52e9dc0bd5cdeb3eb73151e52c28ab3c98dfeb7a2db23bb859f0e8873b39ef"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.5+0/CMake.v3.31.5.armv7l-linux-musleabihf-cxx11.tar.gz"
[[CMake]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "694b1de0dee3d77afec0c28cc342a2507108f59c"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "ff8e85e30eab326cebcdce6f2a57ee0eb04f659c165f33ac4d3f918a59ee5104"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.5+0/CMake.v3.31.5.i686-linux-gnu-cxx03.tar.gz"
[[CMake]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8359f70a31ec73e14275d8b9b5e49998e5bd2537"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "a0a98b26650f0c030534ebdbfe7386f60b206782fcdf6dad06ad6675a2142130"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.5+0/CMake.v3.31.5.i686-linux-gnu-cxx11.tar.gz"
[[CMake]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "43e3372ce6c4b878de496b7ad868714429b1013b"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "2185812040163ccbd126d31e33a15abe635c52e15a7024f6377f91bcbfd1917e"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.5+0/CMake.v3.31.5.i686-linux-musl-cxx03.tar.gz"
[[CMake]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6c43b95b20a27fb6f49ecf747eb7f9db9b364d02"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "de78fd6a59835d2ea4f4f9544f23b18597b57614956a8e85f3235f37d7817f80"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.5+0/CMake.v3.31.5.i686-linux-musl-cxx11.tar.gz"
[[CMake]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "efbcf5fe83b5857a7d99f9116f04217b2714d678"
os = "windows"

    [[CMake.download]]
    sha256 = "9bd57a8d1db9182858dd716493fee55f9daddcf4ba8262dab9ab96e5511aa1c6"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.5+0/CMake.v3.31.5.i686-w64-mingw32-cxx03.tar.gz"
[[CMake]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b31f3fbdb94c505aaacd1de96be74474d24e981f"
os = "windows"

    [[CMake.download]]
    sha256 = "f8b5d15f24bb5d285a0dff6055bde16be3f573ba33843a57794a07254738a412"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.5+0/CMake.v3.31.5.i686-w64-mingw32-cxx11.tar.gz"
[[CMake]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f9a08d022921f00d5ab719302eef8995dfc7da19"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "c8a397e46c425d86282eb918b73beac1c5d3ae0f1462aa183f0bdf069b74766e"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.5+0/CMake.v3.31.5.powerpc64le-linux-gnu-cxx03.tar.gz"
[[CMake]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "985abec66fdb10e29d493f7f9885f73377bb6673"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "3c08589bba6252a16ab1f4e36ace9a92e52151555f22956c430418cbe1c7e0c6"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.5+0/CMake.v3.31.5.powerpc64le-linux-gnu-cxx11.tar.gz"
[[CMake]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "65ff37c42b919cf4792f658ba4ecc2250a66d265"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "22b61c25c6092152d7eae1ece193cc4b1c6838e81f317ef14090e68686fcf96a"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.5+0/CMake.v3.31.5.riscv64-linux-gnu-cxx03.tar.gz"
[[CMake]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "63ad28d845f58fadee4c9d6ae7f0457ffee428a9"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "ec77d0ae9a1a7ce9eb8bcd044e897fa97efab113974bd66b58bcae30005549fb"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.5+0/CMake.v3.31.5.riscv64-linux-gnu-cxx11.tar.gz"
[[CMake]]
arch = "x86_64"
git-tree-sha1 = "421378e23b5f8ad8cef7f1312243818258fc6ec5"
os = "macos"

    [[CMake.download]]
    sha256 = "fb9c2b9c41273cb0151469cabf735681619bc3a4de745d74aca7453fae1c8426"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.5+0/CMake.v3.31.5.x86_64-apple-darwin.tar.gz"
[[CMake]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d535ae2280662e5440ad7fb791ddf8aae2741d2c"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "b87fd21dd64336fc447ec5510aaabd4532984018cbbae593030936efdb07b3be"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.5+0/CMake.v3.31.5.x86_64-linux-gnu-cxx03.tar.gz"
[[CMake]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "513c6a4c9311020ca9216dd063aecc3148a207e1"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "a846e981a02fbf5239ef502d19f1529af45018d9ee39c133b9d839142caee138"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.5+0/CMake.v3.31.5.x86_64-linux-gnu-cxx11.tar.gz"
[[CMake]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "74d2be78be0f5151ca4f3255eeb739daef5cda04"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "eb40368ae1437d97144cbc4213761075651b0ce09028a1df9b2faae8cfbff30b"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.5+0/CMake.v3.31.5.x86_64-linux-musl-cxx03.tar.gz"
[[CMake]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f919f3a7d1971a1d2e6549e9104c3484f667b5a"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "83ed474a85f90f03318a8aac38f03d0eec5c941310e62f6c4c4633ffa0c90099"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.5+0/CMake.v3.31.5.x86_64-linux-musl-cxx11.tar.gz"
[[CMake]]
arch = "x86_64"
git-tree-sha1 = "e0bffc2e6b424d5e9f67a760c965d472080d76a3"
os = "freebsd"

    [[CMake.download]]
    sha256 = "a4486f9c74d369fbe3190c687aeaab4a62ab1b8f7565883061246867cc6f2c08"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.5+0/CMake.v3.31.5.x86_64-unknown-freebsd.tar.gz"
[[CMake]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "683ae0bd6971a4eb5de665a7b0cac258a3ff7e52"
os = "windows"

    [[CMake.download]]
    sha256 = "b813e9468e06db907b805c737eea332e4c99a989c8fa3ee168287d50f1978951"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.5+0/CMake.v3.31.5.x86_64-w64-mingw32-cxx03.tar.gz"
[[CMake]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4f50af62d0625d2800107dba00469e29768e0523"
os = "windows"

    [[CMake.download]]
    sha256 = "b12922b259b721516859935f4130f9fd7d447e90d37d89538e986b4b35748ae1"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.5+0/CMake.v3.31.5.x86_64-w64-mingw32-cxx11.tar.gz"
