[[CMake]]
arch = "aarch64"
git-tree-sha1 = "723e9ac285b1e0eeeddc8bf5fdf57becb6d8211d"
os = "macos"

    [[CMake.download]]
    sha256 = "ecb406019ec4e81fbc298d5fdb4fef0670b183bc05862fde51826aa2edf3722f"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.24.3+0/CMake.v3.24.3.aarch64-apple-darwin.tar.gz"
[[CMake]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "55248c5feb3e1ddd7202605680845607dfce9ad4"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "44cea040449d31fbbc7676f3c77e69e8f189083c82f52940d8a503b47e0674dc"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.24.3+0/CMake.v3.24.3.aarch64-linux-gnu-cxx03.tar.gz"
[[CMake]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1ceb5e8fd9ecc98e02ef6de890a9cd4b828d824c"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "6c322634e802f6059e5aad04899e7a9bc476f38dba49a975e39f5e5de22655dc"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.24.3+0/CMake.v3.24.3.aarch64-linux-gnu-cxx11.tar.gz"
[[CMake]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ce48792951bf90a9a42d09bc437b16f17a973e68"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "d6a7c8c3d709e92be17274526cbe0381633d3e7279684e6b051826734e080b46"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.24.3+0/CMake.v3.24.3.aarch64-linux-musl-cxx03.tar.gz"
[[CMake]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a7999eb5fd1f05b0839f3fa5a4da4769080fe2af"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "973ccc07f40359a14a423bb8b70d5547aec5f9cc5a23483f14f33953ccc42fae"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.24.3+0/CMake.v3.24.3.aarch64-linux-musl-cxx11.tar.gz"
[[CMake]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "abeec1459f96d761dcca33f048e036f13f3f4856"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "453d8a572493cb791bd2fcb0edf4441c09aabc83839148b0f6e14f0dd4eecfb0"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.24.3+0/CMake.v3.24.3.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[CMake]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "be6b69b822e9ba52ee1a4d52a7f778faed26b785"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "2e29bc3ecc43ba84b44204b21336683fe51687ee7b5975a8262edddffef663e1"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.24.3+0/CMake.v3.24.3.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[CMake]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "186501ac6f04d0f84dfac959fefcc886ab47f806"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "9c20af07ccb03cec808778785b7b88a8ef455aa9b1e030692bdf41bd91250111"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.24.3+0/CMake.v3.24.3.armv6l-linux-musleabihf-cxx03.tar.gz"
[[CMake]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "01d08d1bf2f8fbfac15cc8a00fee93dad3a5addb"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "d85e81a846a28e767f32201647c4cf2746dfbedb2a894577dc193eacaf99a648"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.24.3+0/CMake.v3.24.3.armv6l-linux-musleabihf-cxx11.tar.gz"
[[CMake]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "08c4afb2f398ddec77fe299c0205d6fbede86397"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "bdfa323bd1f6089caab441974747d6116fb3f0653533f8cbdfe6e0d9d14fcad6"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.24.3+0/CMake.v3.24.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[CMake]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "80ed9d55c0a07db687e72d87aba81a098b97fd69"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "c773bb0b754d5565a4c2c31c4c5f90323747e7fefeddec88762c10ce615e09c2"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.24.3+0/CMake.v3.24.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[CMake]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0bb764a992f40d07bb4f278a7b0c16a5c8c593b1"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "b12aac37dfe58fac23828887783a7d0c7bf2fbdd3c81ecaf5999341e264c2980"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.24.3+0/CMake.v3.24.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[CMake]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f350e9f2059f320dc1bd99271ce8f9f300e1ac8f"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "0c0d53b37f3d289267966c3ff825d2556445fa52ccea89e00ee68c7b7bfe5990"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.24.3+0/CMake.v3.24.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[CMake]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "940f1a151b9d161b6d125dbc75295eda779ef228"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "ce795c4ce3fdbe7e3ab2dcefd565dd8c3f3841876aa51ad290eb7fdc88d91255"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.24.3+0/CMake.v3.24.3.i686-linux-gnu-cxx03.tar.gz"
[[CMake]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "737a002a9ef9c421ba75f3ae23d0964dd5ef3f9d"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "2284e8c245a98609d7c3476ca1fcd4474ee98433d6ac9b7cc1a7fc5f39e16fb4"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.24.3+0/CMake.v3.24.3.i686-linux-gnu-cxx11.tar.gz"
[[CMake]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "891359666e9cb1cea72b23f30c3666963ab218f7"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "870d8d726985c4e584ca83b1dd43ca2545fa9495091c024a554f29de996d32a1"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.24.3+0/CMake.v3.24.3.i686-linux-musl-cxx03.tar.gz"
[[CMake]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b298e04cffbde1d4e1302d4170f8c1ee240ed458"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "3e92a5018091d93960dcc8d74dabed0fc06617b3e64aad375fb274892377a8fb"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.24.3+0/CMake.v3.24.3.i686-linux-musl-cxx11.tar.gz"
[[CMake]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "94e2487f0cb7b1c3138bb8f3c6bd07ccbc64fc2b"
os = "windows"

    [[CMake.download]]
    sha256 = "39c352e87b866d88c8c62a59e70d00b186d81d9219f141998717e238bd03a5ba"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.24.3+0/CMake.v3.24.3.i686-w64-mingw32-cxx03.tar.gz"
[[CMake]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b71d1548f3d45ebe0c5f8c6e99e1d311eccb677f"
os = "windows"

    [[CMake.download]]
    sha256 = "82a6c8eb0bf5a191b0a6eee6907e9569b93dac2d65a86aae063a1cefead63cc6"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.24.3+0/CMake.v3.24.3.i686-w64-mingw32-cxx11.tar.gz"
[[CMake]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "12833bfb4b2c45774d22e5d1782cfb8338516258"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "9fe472eca45caa8bab35afe9d6f1037a62406be5f43336bb08f655b51aa39949"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.24.3+0/CMake.v3.24.3.powerpc64le-linux-gnu-cxx03.tar.gz"
[[CMake]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4d860df1ca2646762770c59f94319b170e5ca2b0"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "95f0dbbea75444bec154b11e3e73db1c5cdefc916ddb814991e1134b10231e9b"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.24.3+0/CMake.v3.24.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[CMake]]
arch = "x86_64"
git-tree-sha1 = "c2bb9b764fe5bafc8326e55be26bb4fad8149e44"
os = "macos"

    [[CMake.download]]
    sha256 = "7e4f53fa80d50fa48ab19a62b69cba7f9f5a0e181598c0befdeb4e362e94efbf"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.24.3+0/CMake.v3.24.3.x86_64-apple-darwin.tar.gz"
[[CMake]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "09425656bd7b6af0e49fdae5eb5fcb71b1635804"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "537d962e7a736bcf5a22289e167fcf07240f19e957527ba10434a4639de94880"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.24.3+0/CMake.v3.24.3.x86_64-linux-gnu-cxx03.tar.gz"
[[CMake]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9204b6aee818f47624b4c729d675c66b4a399b6b"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "ef29693d4b102672425b44157655564299e89c5e5dac9c2913f464f7eb5d825d"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.24.3+0/CMake.v3.24.3.x86_64-linux-gnu-cxx11.tar.gz"
[[CMake]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e11787109d2951f508ae9bfd12b2f52e9e849c1f"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "92ebfba7952e3ea6586064e37960599c13fd276e2c2f378c9f52ca80bc8010e7"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.24.3+0/CMake.v3.24.3.x86_64-linux-musl-cxx03.tar.gz"
[[CMake]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "62844d31ea64ce107f6a6b56d6f6dc4740f08376"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "b0601ce4b252ca5c11a8cbdfef69683eaa58967c03319083ef120a8f371adf81"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.24.3+0/CMake.v3.24.3.x86_64-linux-musl-cxx11.tar.gz"
[[CMake]]
arch = "x86_64"
git-tree-sha1 = "6db976836e066b5048a65130ac5578e5fcf7cefd"
os = "freebsd"

    [[CMake.download]]
    sha256 = "3a3d1af382d43674919b295cd23e1af3304c1f2dbcdc9c8c79f4cf7986a346ec"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.24.3+0/CMake.v3.24.3.x86_64-unknown-freebsd.tar.gz"
[[CMake]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "de9f7395af9110334644519455a22b462b9990f7"
os = "windows"

    [[CMake.download]]
    sha256 = "7abf4e4d105620ad3725dfd9a6b2ba0a664011838f2cb03618d1ec4994ef5277"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.24.3+0/CMake.v3.24.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[CMake]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "11ec9db447a5f469a10ab83af0be258adab5b95a"
os = "windows"

    [[CMake.download]]
    sha256 = "c798d63bd2e4b24cdb14c0c23b3ef132d8dd006d2dc2bb5fb53e5ef6eabfb759"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.24.3+0/CMake.v3.24.3.x86_64-w64-mingw32-cxx11.tar.gz"
