[[CMake]]
arch = "aarch64"
git-tree-sha1 = "a9590f143a4e43e45598ff72b406b3a2b304617e"
os = "macos"

    [[CMake.download]]
    sha256 = "f9e42554bc3b182b7fccdf6e084392bab8114ffe718f592cf0d67893d277f91f"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.6+0/CMake.v3.31.6.aarch64-apple-darwin.tar.gz"
[[CMake]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "231714f4e1a606673467cbcbd9f030808b0db81f"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "4547a7c155a14b80c4547c820d2627364fccb487a5290d284785f476ab316bc5"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.6+0/CMake.v3.31.6.aarch64-linux-gnu-cxx03.tar.gz"
[[CMake]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f98db3a3c1f757b95241d55be477bf05297f4d17"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "a51013e4e1080248cac10884dff2c751afc8ba9fb7b8fbf85d343d53afb0742a"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.6+0/CMake.v3.31.6.aarch64-linux-gnu-cxx11.tar.gz"
[[CMake]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4802edb74e96698e8ecf6acadb2c26b70b3b040f"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "19fed73dc1f3382cdf7146580a4a5450ea957dfbb61128dd458f15752d833927"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.6+0/CMake.v3.31.6.aarch64-linux-musl-cxx03.tar.gz"
[[CMake]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "708fc430d7715640689701332027690cb2888ca2"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "9139a4ed9079b11c7a57fb21cb0364a9b0c7ddaa7ec21e0a87b00998fdec08e5"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.6+0/CMake.v3.31.6.aarch64-linux-musl-cxx11.tar.gz"
[[CMake]]
arch = "aarch64"
git-tree-sha1 = "511a085856bcaec2d0a1c4a068bb8bb3b96955c8"
os = "freebsd"

    [[CMake.download]]
    sha256 = "f6be701076ee9cb4b89b9a54b5c13ea52098ff5a43e4b1756ea6a8728a6689ca"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.6+0/CMake.v3.31.6.aarch64-unknown-freebsd.tar.gz"
[[CMake]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5ade9e8ff595c33d0323282398e9e042e82fbfd7"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "ba001a69763d0dd8248a7cae601099589cec69698a4fe12f9fcd1e123ddefc11"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.6+0/CMake.v3.31.6.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[CMake]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "895bc186f37269778386cf19afa8c74944c823fc"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "dc08672b950befc252077df7e0b5715886f0362f9f9c4e72d2c323cb201fef0c"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.6+0/CMake.v3.31.6.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[CMake]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7c754204586bda729c05e66c85fd03684b68b9e7"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "fb5aefa18eab732418d39c3e487cfa1a1c2aa87ee1557d7d5afbbc719625a4e7"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.6+0/CMake.v3.31.6.armv6l-linux-musleabihf-cxx03.tar.gz"
[[CMake]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2908aa9df02de73608e652515d9bb46499a1f1d9"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "22169972ef80ad07633274ad46c1235ed3a647942357667759d6860abefc6264"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.6+0/CMake.v3.31.6.armv6l-linux-musleabihf-cxx11.tar.gz"
[[CMake]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e0192fcc47a8a045574aebb8e6f7a11ad602336a"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "d2c62fe7200abf8b1ec0a0dec4ee833ac668cac3677b271e3c864e1a6ffb2730"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.6+0/CMake.v3.31.6.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[CMake]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4c5b9436b4a56367e7888c2dea0276f431febec8"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "ec09eef74293ea3ac1e219a328278f982ab2aaf64c161cd9f53fab4ad42af527"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.6+0/CMake.v3.31.6.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[CMake]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "26b7e4b2e232bee4c77e68d56e699559dd23ab36"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "43621903d839d4bbf6d11d3ec92cbec918d6b36add3a54cbc496ca4b820bf4ff"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.6+0/CMake.v3.31.6.armv7l-linux-musleabihf-cxx03.tar.gz"
[[CMake]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4f3eb710389de0c9ec0b0d4207db857dfead0e05"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "802a1d1b36a11757ffa113571ad606ab099098526d2b1d2d4e3c37bf7b7a2866"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.6+0/CMake.v3.31.6.armv7l-linux-musleabihf-cxx11.tar.gz"
[[CMake]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3461f7783253933405df6c62ef0543f2ceb4c72b"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "d9249c4565dc37b68fd47e4b1a1f4f36282af052127b9df2d20886b433244a8f"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.6+0/CMake.v3.31.6.i686-linux-gnu-cxx03.tar.gz"
[[CMake]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "99a072c00490dd417f8a8889225154c7f85c0723"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "01364ac4279d83896e006164513eb7105b0f57efce9ae842a679bfd3839f2bea"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.6+0/CMake.v3.31.6.i686-linux-gnu-cxx11.tar.gz"
[[CMake]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3dbd61efcafc9295c5259f3a24059c82b2bff408"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "9eed07a7e4aa42d50b84aa8d3e3c08a109abc6b6765fdc3fa464544c436b0b35"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.6+0/CMake.v3.31.6.i686-linux-musl-cxx03.tar.gz"
[[CMake]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "64eac8d2d5abaa80cc879da004c08a9929089db8"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "027514de3396852787a106c5a2469ddb72747cf35e73db0bfedd4c66515d82b4"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.6+0/CMake.v3.31.6.i686-linux-musl-cxx11.tar.gz"
[[CMake]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "655b364c213db14b4c4cec7f1a451dcf71b8b2b1"
os = "windows"

    [[CMake.download]]
    sha256 = "7ca324035dc34f7d79e8b45c2d0282dbd5ca68622e2a1e0bbf197b0e6f9b50bb"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.6+0/CMake.v3.31.6.i686-w64-mingw32-cxx03.tar.gz"
[[CMake]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f7eaf9221de215f0556cda65b5608a8173da8d81"
os = "windows"

    [[CMake.download]]
    sha256 = "5f88e16a312d544e4b1bac178fdbeac21b7b93ae12e43f1644754e85450876bb"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.6+0/CMake.v3.31.6.i686-w64-mingw32-cxx11.tar.gz"
[[CMake]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e6bb1c0c3ecc8d06a553c01b7c69327b4078ebba"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "b8a3f09fe5919edc9a6aabf0d0497ee8ddaeadf3e7afc1f57d59f02bcd87a4be"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.6+0/CMake.v3.31.6.powerpc64le-linux-gnu-cxx03.tar.gz"
[[CMake]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7de5db915a935adfd1e3f9615262f17f1050e89a"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "aabfb3e6019e76a6bc2ba74aa13456ee8665eadef06117ffd8eeae519309d460"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.6+0/CMake.v3.31.6.powerpc64le-linux-gnu-cxx11.tar.gz"
[[CMake]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b78be63e891c25513cd5322c0c051ccf11c8f6b6"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "e1aece331180cf8ba66d187e709946e50a765d3fc91fc82721883e46ce052df7"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.6+0/CMake.v3.31.6.riscv64-linux-gnu-cxx03.tar.gz"
[[CMake]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2bf336c9222c75f19cb808a963709782f157fd4c"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "a193c2809f765d538be6cf7b92d1d7787c447e33a2df58437ad6c48c84ee3c60"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.6+0/CMake.v3.31.6.riscv64-linux-gnu-cxx11.tar.gz"
[[CMake]]
arch = "x86_64"
git-tree-sha1 = "7ae9ddae4b7219084e4222da1237cf0802357c7e"
os = "macos"

    [[CMake.download]]
    sha256 = "27edf406ccbad4983c5b22eaef16a2fbd47c0b3d860be6dc7806f500d2a6891c"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.6+0/CMake.v3.31.6.x86_64-apple-darwin.tar.gz"
[[CMake]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "456e1702bcbfc77976509add148c98c22e569982"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "c7c339e29fc4fd3ba08ff1024521605d7ea2628bdab3b6e14fc8ff72350899bd"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.6+0/CMake.v3.31.6.x86_64-linux-gnu-cxx03.tar.gz"
[[CMake]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "030bac1e80c1775218ad28a5599ec558e49d1e34"
libc = "glibc"
os = "linux"

    [[CMake.download]]
    sha256 = "7172dfd38633ef16e937f02b5c16b33f658e04d17c208fc86b80e6d3f24f471c"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.6+0/CMake.v3.31.6.x86_64-linux-gnu-cxx11.tar.gz"
[[CMake]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "70599da77ddf51c34e1043e934ea9aa25a62d5fc"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "6567f685740dce9fec03c97f8e9f5c676dbbb6c30fe71cc39ed96311a866db0d"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.6+0/CMake.v3.31.6.x86_64-linux-musl-cxx03.tar.gz"
[[CMake]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db67336af9bf24e2b9519fcc67d9b934e5647add"
libc = "musl"
os = "linux"

    [[CMake.download]]
    sha256 = "6910c1de515c5bb6222f053cf57adf96c804273083372f5cebacca5def2fe85a"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.6+0/CMake.v3.31.6.x86_64-linux-musl-cxx11.tar.gz"
[[CMake]]
arch = "x86_64"
git-tree-sha1 = "606c2c8f948e6b948edbf3d838ed53081888c92e"
os = "freebsd"

    [[CMake.download]]
    sha256 = "c47adc2f546049101bb86ce707df7a148293cfc1011f4f5448ccbd276d9493ed"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.6+0/CMake.v3.31.6.x86_64-unknown-freebsd.tar.gz"
[[CMake]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9510c0c6f6a2a47116dc544efc48832f26490efc"
os = "windows"

    [[CMake.download]]
    sha256 = "19e3ef3c3eb2451feb97773d8873f3455c625ab095abab5a42d483abf5bb4ed7"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.6+0/CMake.v3.31.6.x86_64-w64-mingw32-cxx03.tar.gz"
[[CMake]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "53751920df06616a64e7ad1116612e27ec7d70d5"
os = "windows"

    [[CMake.download]]
    sha256 = "e84ad494b893c900892482e597fc2a26f080bdc5da98c21e79f755d3fe968e3d"
    url = "https://github.com/JuliaBinaryWrappers/CMake_jll.jl/releases/download/CMake-v3.31.6+0/CMake.v3.31.6.x86_64-w64-mingw32-cxx11.tar.gz"
